# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

"""Serve logs process"""
import os

import flask

from airflow.configuration import conf


# python flask 是一个流行的web框架，
# 此处拉起一个日志服务，通过访问: localhost:8793/log/filename  可以访问本地日志。
def serve_logs():
    """Serves logs generated by Worker"""
    print("Starting flask")
    flask_app = flask.Flask(__name__)

    # 定义页面url对应后台的接口映射
    @flask_app.route('/log/<path:filename>')
    def serve_logs_view(filename):  # pylint: disable=unused-variable
        # 从airflow.cfg配置文件中获取base_log_folder的日志
        log_directory = os.path.expanduser(conf.get('logging', 'BASE_LOG_FOLDER'))
        return flask.send_from_directory(
            log_directory, filename, mimetype="application/json", as_attachment=False
        )

    # 获取airflow.cfg中配置的端口
    worker_log_server_port = conf.getint('celery', 'WORKER_LOG_SERVER_PORT')
    # 启动flask 微型web服务框架
    flask_app.run(host='0.0.0.0', port=worker_log_server_port)
